### ISSUE TITLE
Lowercase the config.toml keys and config.KEYS

### ISSUE THREAD

**Issue by AiroPi** [mybot-organization/mybot#139]
There is no need to have the config keys in uppercase imo.

From the code perspective, however, it can be a way to tell "this is CONSTANT", but the "config" object should be enough to tell that these values are constants.
Something like `config.bot_name` feel more natural than `config.BOT_NAME` in my eyes. 

However, the config object also contains some environ variables such a POSTGRES_USER...
I think this should just not be the case, as these values are already accessible through os.environ.
Their presence here is only used to define some default values for these env vars, but they should not be defaulted anyway to avoid any error with the database instantiation.

**Comment by AiroPi** [comment]
@nc0fr can I have your pov on this ?

**Comment by nc0fr** [comment]
I definitely am for this change, `CONSTANT_CASE` is reserved to constant values defined within the code (and are expected to be inlined), whereas configuration keys are external. You could for instance have hot code reloading happening when changing the configuration.
